### PR TITLE
Move library to root of repository

### PR DESCRIPTION
**Pull request by per1234**
A popular library installation technique is to download the library via GitHub's **Clone or download > Download ZIP** and then use the Arduino IDE's **Sketch > Include Library > Add .ZIP Library** on the downloaded file. This requires the library to be in the root of the repository, not in a subfolder. If the library is not in the root of the repository this installation technique fails:
```
Specified folder/zip file does not contain a valid library
```
This move is also required if you wanted to [add your library to the Arduino Library Manager index](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ), which provides an even easier installation option.

### CODE REVIEW

**Comment by astuder** [comment]
@per1234 thank you for your contributions. Really appreciated! 

Before I merge this PR, what is the best practice for additional content? Like in this case the KiCad project and pictures to illustrate readme.

**Comment by per1234** [comment]
From the Arduino Library specification;
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#extra-documentation

>An extras folder can be used by the developer to put documentation or other items to be bundled with the library. Remember that files placed inside this folder will increase the size of the library, so putting a 20MB PDF in a library that weights a few kilobytes may not be such a good idea.
>
>The content of the extras folder is totally ignored by the IDE; you are free to put anything inside such as supporting documentation, etc.

So I think best practices would be to move those files under extras. I'm happy to make that modification to this PR if you agree with that change.

**Comment by astuder** [comment]
Ok, then let's do it by the book :-)

**Comment by per1234** [comment]
OK, I made the change to the PR via a force push.

**Comment by astuder** [comment]
thanks!

**Pull request merged**
